# Generated by Django 4.0.3 on 2022-04-08 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Primo',
            fields=[
                ('rol', models.IntegerField(primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('nick', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField()),
                ('primo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.primo')),
            ],
        ),
    ]
