# Generated by Django 4.0.3 on 2022-04-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_alter_turno_checkout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turno',
            new_name='Shift',
        ),
    ]
