# Generated by Django 4.0.3 on 2022-04-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_rename_turno_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='primo',
            name='schedule',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
