# Generated by Django 4.0.4 on 2022-09-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_primo_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PardonedShift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('block', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Shift',
            new_name='StampedShift',
        ),
        migrations.AddConstraint(
            model_name='pardonedshift',
            constraint=models.UniqueConstraint(fields=('block', 'date'), name='unique_block_date'),
        ),
    ]
